# Generated by Django 3.0.5 on 2020-05-10 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='me', max_length=120),
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=datetime.datetime(2020, 5, 10, 7, 9, 48, 613562, tzinfo=utc)),
        ),
    ]
