# Generated by Django 3.0.5 on 2020-05-11 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200510_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=datetime.datetime(2020, 5, 11, 11, 34, 17, 706505, tzinfo=utc)),
        ),
    ]
